name: dola
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - tqdm
  - pytorch-gpu
  - pip:
    - datasets
    - accelerate
    - openai
    - shortuuid
    - transformers